# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'current_controller.ui'
#
# Created: Mon Nov  7 13:04:39 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1062, 806)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setMargin(10)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayoutA = QtGui.QVBoxLayout()
        self.verticalLayoutA.setSpacing(0)
        self.verticalLayoutA.setMargin(10)
        self.verticalLayoutA.setObjectName(_fromUtf8("verticalLayoutA"))
        self.labelA = QtGui.QLabel(self.centralwidget)
        self.labelA.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelA.setObjectName(_fromUtf8("labelA"))
        self.verticalLayoutA.addWidget(self.labelA)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.onOffButtonA = QtGui.QPushButton(self.centralwidget)
        self.onOffButtonA.setMinimumSize(QtCore.QSize(40, 40))
        self.onOffButtonA.setMaximumSize(QtCore.QSize(50, 100))
        self.onOffButtonA.setCheckable(True)
        self.onOffButtonA.setAutoDefault(False)
        self.onOffButtonA.setObjectName(_fromUtf8("onOffButtonA"))
        self.horizontalLayout_2.addWidget(self.onOffButtonA)
        self.verticalLayoutA.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.currentValueLabelA = QtGui.QLabel(self.centralwidget)
        self.currentValueLabelA.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentValueLabelA.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentValueLabelA.setObjectName(_fromUtf8("currentValueLabelA"))
        self.horizontalLayout_5.addWidget(self.currentValueLabelA)
        self.currentLimitLabelA = QtGui.QLabel(self.centralwidget)
        self.currentLimitLabelA.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentLimitLabelA.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentLimitLabelA.setObjectName(_fromUtf8("currentLimitLabelA"))
        self.horizontalLayout_5.addWidget(self.currentLimitLabelA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.currentValueSpinBoxA = QtGui.QSpinBox(self.centralwidget)
        self.currentValueSpinBoxA.setMaximum(1000)
        self.currentValueSpinBoxA.setProperty(_fromUtf8("value"), 0)
        self.currentValueSpinBoxA.setObjectName(_fromUtf8("currentValueSpinBoxA"))
        self.horizontalLayout_4.addWidget(self.currentValueSpinBoxA)
        self.currentLimitSpinBoxA = QtGui.QSpinBox(self.centralwidget)
        self.currentLimitSpinBoxA.setMaximum(1000)
        self.currentLimitSpinBoxA.setProperty(_fromUtf8("value"), 0)
        self.currentLimitSpinBoxA.setObjectName(_fromUtf8("currentLimitSpinBoxA"))
        self.horizontalLayout_4.addWidget(self.currentLimitSpinBoxA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayoutA.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dialA = QtGui.QDial(self.centralwidget)
        self.dialA.setEnabled(True)
        self.dialA.setMinimumSize(QtCore.QSize(75, 75))
        self.dialA.setMaximumSize(QtCore.QSize(100, 100))
        self.dialA.setMaximum(1000)
        self.dialA.setProperty(_fromUtf8("value"), 0)
        self.dialA.setNotchesVisible(True)
        self.dialA.setObjectName(_fromUtf8("dialA"))
        self.horizontalLayout.addWidget(self.dialA)
        self.verticalLayoutA.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addLayout(self.verticalLayoutA)
        self.verticalLayoutB = QtGui.QVBoxLayout()
        self.verticalLayoutB.setSpacing(0)
        self.verticalLayoutB.setMargin(10)
        self.verticalLayoutB.setObjectName(_fromUtf8("verticalLayoutB"))
        self.labelB = QtGui.QLabel(self.centralwidget)
        self.labelB.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelB.setObjectName(_fromUtf8("labelB"))
        self.verticalLayoutB.addWidget(self.labelB)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.onOffButtonB = QtGui.QPushButton(self.centralwidget)
        self.onOffButtonB.setMinimumSize(QtCore.QSize(40, 40))
        self.onOffButtonB.setMaximumSize(QtCore.QSize(50, 100))
        self.onOffButtonB.setCheckable(True)
        self.onOffButtonB.setAutoDefault(False)
        self.onOffButtonB.setObjectName(_fromUtf8("onOffButtonB"))
        self.horizontalLayout_6.addWidget(self.onOffButtonB)
        self.verticalLayoutB.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.currentValueLabelB = QtGui.QLabel(self.centralwidget)
        self.currentValueLabelB.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentValueLabelB.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentValueLabelB.setObjectName(_fromUtf8("currentValueLabelB"))
        self.horizontalLayout_8.addWidget(self.currentValueLabelB)
        self.currentLimitLabelB = QtGui.QLabel(self.centralwidget)
        self.currentLimitLabelB.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentLimitLabelB.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentLimitLabelB.setObjectName(_fromUtf8("currentLimitLabelB"))
        self.horizontalLayout_8.addWidget(self.currentLimitLabelB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.currentValueSpinBoxB = QtGui.QSpinBox(self.centralwidget)
        self.currentValueSpinBoxB.setMaximum(1000)
        self.currentValueSpinBoxB.setProperty(_fromUtf8("value"), 0)
        self.currentValueSpinBoxB.setObjectName(_fromUtf8("currentValueSpinBoxB"))
        self.horizontalLayout_9.addWidget(self.currentValueSpinBoxB)
        self.currentLimitSpinBoxB = QtGui.QSpinBox(self.centralwidget)
        self.currentLimitSpinBoxB.setMaximum(1000)
        self.currentLimitSpinBoxB.setProperty(_fromUtf8("value"), 0)
        self.currentLimitSpinBoxB.setObjectName(_fromUtf8("currentLimitSpinBoxB"))
        self.horizontalLayout_9.addWidget(self.currentLimitSpinBoxB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayoutB.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.dialB = QtGui.QDial(self.centralwidget)
        self.dialB.setEnabled(True)
        self.dialB.setMinimumSize(QtCore.QSize(75, 75))
        self.dialB.setMaximumSize(QtCore.QSize(100, 100))
        self.dialB.setMaximum(1000)
        self.dialB.setProperty(_fromUtf8("value"), 0)
        self.dialB.setNotchesVisible(True)
        self.dialB.setObjectName(_fromUtf8("dialB"))
        self.horizontalLayout_10.addWidget(self.dialB)
        self.verticalLayoutB.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayoutB)
        self.verticalLayoutC = QtGui.QVBoxLayout()
        self.verticalLayoutC.setSpacing(0)
        self.verticalLayoutC.setMargin(10)
        self.verticalLayoutC.setObjectName(_fromUtf8("verticalLayoutC"))
        self.labelC = QtGui.QLabel(self.centralwidget)
        self.labelC.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelC.setObjectName(_fromUtf8("labelC"))
        self.verticalLayoutC.addWidget(self.labelC)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.onOffButtonC = QtGui.QPushButton(self.centralwidget)
        self.onOffButtonC.setMinimumSize(QtCore.QSize(40, 40))
        self.onOffButtonC.setMaximumSize(QtCore.QSize(50, 100))
        self.onOffButtonC.setCheckable(True)
        self.onOffButtonC.setAutoDefault(False)
        self.onOffButtonC.setObjectName(_fromUtf8("onOffButtonC"))
        self.horizontalLayout_12.addWidget(self.onOffButtonC)
        self.verticalLayoutC.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.currentValueLabelC = QtGui.QLabel(self.centralwidget)
        self.currentValueLabelC.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentValueLabelC.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentValueLabelC.setObjectName(_fromUtf8("currentValueLabelC"))
        self.horizontalLayout_14.addWidget(self.currentValueLabelC)
        self.currentLimitLabelC = QtGui.QLabel(self.centralwidget)
        self.currentLimitLabelC.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentLimitLabelC.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentLimitLabelC.setObjectName(_fromUtf8("currentLimitLabelC"))
        self.horizontalLayout_14.addWidget(self.currentLimitLabelC)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.currentValueSpinBoxC = QtGui.QSpinBox(self.centralwidget)
        self.currentValueSpinBoxC.setMaximum(1000)
        self.currentValueSpinBoxC.setProperty(_fromUtf8("value"), 0)
        self.currentValueSpinBoxC.setObjectName(_fromUtf8("currentValueSpinBoxC"))
        self.horizontalLayout_15.addWidget(self.currentValueSpinBoxC)
        self.currentLimitSpinBoxC = QtGui.QSpinBox(self.centralwidget)
        self.currentLimitSpinBoxC.setMaximum(1000)
        self.currentLimitSpinBoxC.setProperty(_fromUtf8("value"), 0)
        self.currentLimitSpinBoxC.setObjectName(_fromUtf8("currentLimitSpinBoxC"))
        self.horizontalLayout_15.addWidget(self.currentLimitSpinBoxC)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayoutC.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.dialC = QtGui.QDial(self.centralwidget)
        self.dialC.setEnabled(True)
        self.dialC.setMinimumSize(QtCore.QSize(75, 75))
        self.dialC.setMaximumSize(QtCore.QSize(100, 100))
        self.dialC.setMaximum(1000)
        self.dialC.setProperty(_fromUtf8("value"), 0)
        self.dialC.setNotchesVisible(True)
        self.dialC.setObjectName(_fromUtf8("dialC"))
        self.horizontalLayout_16.addWidget(self.dialC)
        self.verticalLayoutC.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11.addLayout(self.verticalLayoutC)
        self.verticalLayoutD = QtGui.QVBoxLayout()
        self.verticalLayoutD.setSpacing(0)
        self.verticalLayoutD.setMargin(10)
        self.verticalLayoutD.setObjectName(_fromUtf8("verticalLayoutD"))
        self.labelD = QtGui.QLabel(self.centralwidget)
        self.labelD.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelD.setObjectName(_fromUtf8("labelD"))
        self.verticalLayoutD.addWidget(self.labelD)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.onOffButtonD = QtGui.QPushButton(self.centralwidget)
        self.onOffButtonD.setMinimumSize(QtCore.QSize(40, 40))
        self.onOffButtonD.setMaximumSize(QtCore.QSize(50, 100))
        self.onOffButtonD.setCheckable(True)
        self.onOffButtonD.setAutoDefault(False)
        self.onOffButtonD.setObjectName(_fromUtf8("onOffButtonD"))
        self.horizontalLayout_17.addWidget(self.onOffButtonD)
        self.verticalLayoutD.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.currentValueLabelD = QtGui.QLabel(self.centralwidget)
        self.currentValueLabelD.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentValueLabelD.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentValueLabelD.setObjectName(_fromUtf8("currentValueLabelD"))
        self.horizontalLayout_19.addWidget(self.currentValueLabelD)
        self.currentLimitLabelD = QtGui.QLabel(self.centralwidget)
        self.currentLimitLabelD.setMaximumSize(QtCore.QSize(16777215, 25))
        self.currentLimitLabelD.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentLimitLabelD.setObjectName(_fromUtf8("currentLimitLabelD"))
        self.horizontalLayout_19.addWidget(self.currentLimitLabelD)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.currentValueSpinBoxD = QtGui.QSpinBox(self.centralwidget)
        self.currentValueSpinBoxD.setMaximum(1000)
        self.currentValueSpinBoxD.setProperty(_fromUtf8("value"), 0)
        self.currentValueSpinBoxD.setObjectName(_fromUtf8("currentValueSpinBoxD"))
        self.horizontalLayout_20.addWidget(self.currentValueSpinBoxD)
        self.currentLimitSpinBoxD = QtGui.QSpinBox(self.centralwidget)
        self.currentLimitSpinBoxD.setMaximum(1000)
        self.currentLimitSpinBoxD.setProperty(_fromUtf8("value"), 0)
        self.currentLimitSpinBoxD.setObjectName(_fromUtf8("currentLimitSpinBoxD"))
        self.horizontalLayout_20.addWidget(self.currentLimitSpinBoxD)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        self.verticalLayoutD.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.dialD = QtGui.QDial(self.centralwidget)
        self.dialD.setEnabled(True)
        self.dialD.setMinimumSize(QtCore.QSize(75, 75))
        self.dialD.setMaximumSize(QtCore.QSize(100, 100))
        self.dialD.setMaximum(1000)
        self.dialD.setProperty(_fromUtf8("value"), 0)
        self.dialD.setNotchesVisible(True)
        self.dialD.setObjectName(_fromUtf8("dialD"))
        self.horizontalLayout_21.addWidget(self.dialD)
        self.verticalLayoutD.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_11.addLayout(self.verticalLayoutD)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CurrentController", None, QtGui.QApplication.UnicodeUTF8))
        self.labelA.setText(QtGui.QApplication.translate("MainWindow", "Channel A", None, QtGui.QApplication.UnicodeUTF8))
        self.onOffButtonA.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.currentValueLabelA.setText(QtGui.QApplication.translate("MainWindow", "mA", None, QtGui.QApplication.UnicodeUTF8))
        self.currentLimitLabelA.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.labelB.setText(QtGui.QApplication.translate("MainWindow", "Channel B", None, QtGui.QApplication.UnicodeUTF8))
        self.onOffButtonB.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.currentValueLabelB.setText(QtGui.QApplication.translate("MainWindow", "mA", None, QtGui.QApplication.UnicodeUTF8))
        self.currentLimitLabelB.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.labelC.setText(QtGui.QApplication.translate("MainWindow", "Channel C", None, QtGui.QApplication.UnicodeUTF8))
        self.onOffButtonC.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.currentValueLabelC.setText(QtGui.QApplication.translate("MainWindow", "mA", None, QtGui.QApplication.UnicodeUTF8))
        self.currentLimitLabelC.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.labelD.setText(QtGui.QApplication.translate("MainWindow", "Channel D", None, QtGui.QApplication.UnicodeUTF8))
        self.onOffButtonD.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.currentValueLabelD.setText(QtGui.QApplication.translate("MainWindow", "mA", None, QtGui.QApplication.UnicodeUTF8))
        self.currentLimitLabelD.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))

