#define SERIAL_RATE 115200
#define SOFT_SERIAL_RATE 115200
#define DISPLAY_RX_PIN 8
#define DISPLAY_TX_PIN 9
#define TIMER1_PERIOD 1000
#define UPDATE_DISPLAY_PERIOD 200000
#define CLEAR_DISPLAY_PERIOD_RATIO 5000
#define MSG_SIZE 20
#define LIGHT_VALUE_LOW 0
#define LIGHT_VALUE_HIGH 50

#define POTENTIOMETER_VALUE_MIN 0
#define POTENTIOMETER_VALUE_MAX 1023
#define POTENTIOMETER_DISPLAY_MIN 0
#define POTENTIOMETER_DISPLAY_MAX 100

#define CHANNEL_COUNT 4

#define DAC_CS 10
#define DAC_VALUE_MIN 3205
#define DAC_VALUE_MAX 1067
#define DAC_VALUE_OFF 4095

#define IO_CS_PIN  3
#define IO_INTERRUPT 0
#define INTERRUPT_DEBOUNCE_MS 200

#define SWITCH_A_IO_PIN 0
#define SWITCH_B_IO_PIN 1
#define SWITCH_C_IO_PIN 2
#define SWITCH_D_IO_PIN 3
#define SWITCH_SET_IO_PIN 4
#define SWITCH_LIGHT_IO_PIN 5
