#define DISPLAY_RX 8
#define DISPLAY_TX 9
#define UPDATE_DISPLAY_PERIOD 200000
#define CLEAR_DISPLAY_PERIOD_RATIO 5000
#define MSG_SIZE 20
#define LIGHT_VALUE_LOW 0
#define LIGHT_VALUE_HIGH 50

#define POTENTIOMETER_VALUE_MIN 0
#define POTENTIOMETER_VALUE_MAX 1023
#define POTENTIOMETER_DISPLAY_MIN 0
#define POTENTIOMETER_DISPLAY_MAX 100

#define CHANNEL_COUNT 4
